spring:
  datasource:
    url: jdbc:mysql://localhost:3306/racetrack_db
    username: user
    password: password
  jpa:
    open-in-view: false
  data:
    mongodb:
      database: racetrack-db
      username: root
      password: root

